# Generated by Django 4.1.3 on 2022-12-10 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('batch', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('fees', models.BooleanField()),
            ],
        ),
    ]
